### ISSUE TITLE
Compute: Control barrier and shared memory within the local work group

### ISSUE THREAD

**Issue by jozefkucia** [KhronosGroup/GLSL#10]
The GLSL spec isn't very clear if a control barrier is all that is needed to synchronize access to shared memory in compute shaders. There are two options:
- `barrier()` synchronizes execution order and makes writes to shared memory visible to other invocations with the local work group,
- `barrier()` synchronizes execution and additionally `memoryBarrierShared()` is required in order to make memory writes visible to other invocations within the local work group.

There is language in the GLSL spec (section 8.16 Shader Invocation Control Functions) that says:

> The function **barrier()** provides a partially defined order of execution between shader invocations. This ensures that values written by one invocation prior to a given static instance of **barrier()** can be safely 
> read by other invocations after their call to the same static instance **barrier()**.

The above quotation suggests that `barrier()` is sufficient to synchronize access to shared memory in compute shaders. It's worth to mention that this language was initially introduced in `ARB_tessellation_shaders`.

On the other hand, the SPIR-V spec states explicitly that control barriers make writes visibile only for tessellation shaders:

> When used with the **TessellationControl** execution model, it also implicitly synchronizes the **Output** Storage Class:
> Writes to **Output** variables performed by any invocation executed prior to a **OpControlBarrier** will be visible to any other invocation after return from that **OpControlBarrier**.

So, are `memoryBarrierShared()` barriers required together with control barriers in compute shaders in order to make memory writes visible to other invocations within the local work group? Is SPIR-V different than GLSL?

**Comment by pdaniell-nv** [comment]
Thanks for your bug report. It appears this issue is more subtle that I realized and it needs some internal discussion to resolve. We would like to resolve it the same way for OpenGL and OpenGL ES, which requires some reconciliation.

Tagging this as "Resolving inside Khronos" and we'll report back. In the meantime, the safest thing to do is to use a memoryBarrier*() in addition to the control-flow barrier() to guarantee the memory you want to access is synchronized at that point. For the purposes of tessellation control outputs, barrier() alone is fine.

**Comment by pdaniell-nv** [comment]
https://gitlab.khronos.org/opengl/GLSL/issues/24

**Comment by pdaniell-nv** [comment]
We have discussed this internally and will issue an updated specification soon. The conclusion is that barrier() by itself will synchronize shared memory, and only shared memory, and memoryBarrierShared() is not necessary. The other memory barriers are necessary before and/or after barrier() to synchronize the other memory types.

**Comment by pdaniell-nv** [comment]
This should now be resolved in the latest GLSL/ESSL spec release. Closing.

**Comment by jozefkucia** [comment]
> We have discussed this internally and will issue an updated specification soon. The conclusion is that barrier() by itself will synchronize shared memory, and only shared memory, and it's not necessary to use memoryBarrierShared() with barrier() for shared memory.

The latest GLSL spec says:
>In order to achieve ordering with respect to reads and writes to shared variables, a combination of
control  flow  and  memory  barriers  must  be  employed  using  the barrier()  and  memoryBarrier() functions

Do I understand it correctly that the final decision is that memoryBarrier() is necessary together with barrier() for shared memory?

**Comment by pdaniell-nv** [comment]
Hmm, this was an error. The ESSL spec should have picked up the GLSL semantics, not the other way round. Reopening.

**Comment by pdaniell-nv** [comment]
This should be fixed in the latest GLSL and ESSL specs:
- https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.html
- https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html

**Comment by ikapoura** [comment]
I stumbled upon an issue where memoryBarrierShared() did not synchronize the writes to a shared array inside a for-loop with the reads to the same shared array inside a later for-loop which was solved by using only barrier().

There is a text in the spec in 8.17 that says "_When these functions return, the effects of any memory stores performed using coherent variables prior to the call will be visible to any **future** coherent access to the same memory performed by any other shader invocation._" and the future word is specified as "_An access is only a future access if a happens-before relation can be established between the store and the load._"

This implies that there is a possibility that a happens-before relation **cannot** be established thereby making memoryBarrierShared() not do anything. Combining it with the first quote which mentions **coherent access to the same memory** it means that the happens-before relation checks for read-write to specific memory and not read-writes to a variable in general (e.g. a shared array).

I want to ask if the memoryBarrierShared() is any useful because it seems to only create confusion.
