### ISSUE TITLE
Shared memory in raygen shader?

### ISSUE THREAD

**Issue by sayan1an** [KhronosGroup/GLSL#123]
1. Is it possible to have access to shared/scratchpad memory in Raygen shaders? If not, why? 
2. Is it possible to have the usual set of memory barriers in Raygen shaders?

**Comment by dgkoch** [comment]
> Is it possible to have access to shared/scratchpad memory in Raygen shaders? If not, why?

No. Because the thread packing isn't defined raygen shaders (or any ray pipeline stage), similarly to how there is no shared memory available in vertex or fragment shaders. 

> Is it possible to have the usual set of memory barriers in Raygen shaders?

Yes. You can use the memoryBarrier*() commands (ie the ones that are available in all shader stages), but not the barrier()/groupMemoryBarrier() commands that are compute-only. 

Do you think any of this is unclear in the spec?

**Comment by sayan1an** [comment]
> 
> 
> > Is it possible to have access to shared/scratchpad memory in Raygen shaders? If not, why?
> 
> No. Because the thread packing isn't defined raygen shaders (or any ray pipeline stage), similarly to how there is no shared memory available in vertex or fragment shaders.

Are there any plans to add support for shared memory in raygen shaders? It seems to me raygen shaders are closer in principle to the compute pipeline rather than rasterization pipeline and I would prefer to think of raygen as a superset of compute shaders. Looking at the API, it seems raygen is missing the worgorup definitions but it is unclear to me why this was omitted? Perhaps raygen doesn't map well to the SM/CU architecture? Then there are RayQueries which can be used from any shader stage. Does the extra flexibility come at the cost of performance?

For now, I can see a few options in the absence of shared memory in raygen shaders -
1. Use SSBOs - I can make the memory accesses coherent but need to reserve a large pool of memory. 
2. Use fixed-sized arrays in the shader but I am not sure whether they are stored in registers or spill over to some other memory? If so, which type and is it consistent across drivers and vendors?

Any suggestions?

> Do you think any of this is unclear in the spec?
There are not many details available on raytracing extensions on the official Vulkan 1.2 specs and GLSL 4.6 specs. I usually refer to https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing.txt and code samples from various authors.

**Comment by dgkoch** [comment]
There are no plans to expose shared memory in raygen shaders. As I said before the mapping of rays to invocations (ie the thread packing) is not exposed in the ray tracing shader stages. That is also why the workgroup builtins are not available. 

> I would prefer to think of raygen as a superset of compute shaders

That might be your preference, but that is not the model that is exposed ;-) 
In practise they might be implemented as compute shaders under the covers (as they execute on compute queues in Vulkan) but that is an implementation detail. 

If you really want the full compute model, you'd need to use ray queries as you noted. The extra flexibility comes at the cost of needing to manually implement (possibly significant) portions of the ray tracing pipeline infrastructure if you need it.  Ray pipelines are designed to allow a great deal of implementation flexibility in how they are implemented, and the details of that can and will very significantly across drivers / chip families / vendors / time. 

As for how best to design your algorithm, I think the scope of that is a little beyond this issue tracker. 

The GLSL 4.6 spec obviously doesn't have any details on the ray tracing extension, because it pre-dates the ray tracing functionality. The best sources for your Vulkan information are the following specs:

Vulkan Specifications:
 - [VK_KHR_ray_tracing](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_ray_tracing)
 - [VK_KHR_deferred_host_operations](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_deferred_host_operations)
- [VK_KHR_pipeline_library](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_pipeline_library)

SPIR-V Specifications: 
- [SPV_KHR_ray_tracing](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.html)
- [SPV_KHR_ray_query](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_query.html)

GLSL Extension Specifications: 
- [GLSL_EXT_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing.txt)
- [GLSL_EXT_ray_query](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt)
