### ISSUE TITLE
Extending bit width control inside of GLSL

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/GLSL#38]
Originally filed by @Cazadorro in KhronosGroup/Vulkan-Ecosystem:

> Suggestions to add new integer types in vulkan GLSL, such as int24/uint24 and int10/uint10 which map into 32bit float and 16bit float mantissas respectively, or potentially more control. Submitting based on the recommendation here.
> 
> Currently there are some architectures that exist where integer performance is worse that floating point performance. For example, Nvidia hardware is like this and in CUDA, they've provided the ability to do 24bit integer arithmetic through intrinsic functions that take advantage of the mantissa of their floating point units. Integer intensive operations could see a benefit from the utilization of either/both integer and floating point hardware if the programmer took careful consideration of the range of an 24bit integer. Some GPUs do not have 1:1 FPU to ALU which causes a difference in performance in favor of floating point operations. Such optimizations may be possible with precision qualifiers in GLSL, but since it applies globally you would be ignoring integer ALUs potentially (among normal small integer optimizations). It is also unclear to me whether global precision qualifiers are still valid either in Vulkan or recent versions of OpenGL with GLSL.
> 
> SPIR-V appears to already support different bit widths for float and integer types. This would seem to indicate no changes to SPIR-V would need to be done in order for such an extension to be adopted.
> 
> If one could specify the bits used in integers like so it could map directly into SPIR-V with out issue, and it would be up to the vendor to implement the JIT optimization that would utilize floating point units instead of integer units or what ever internal process they desire.
> 
> It may be the case that instead of adding new syntax for only int24 and int10, since the same applies to int54, one should be able to arbitrarily specify bit width of their integers in glsl ie int4, int18 int8 etc... which may have further optimization effects for systems with multiple smaller arithmetic units for integers. This could take place in two different extensions for GLSL, one for up to 32bits and one for up to 64bits.

See original issue for some relevant discussion not captured here (https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/34)

**Comment by Cazadorro** [comment]
@jeffbolznv I'm not sure if it is the case, but the idea originally was that you could increase your integer throughput using both FPUs and ALUs at the same time, but since you would presumably would still need to emulate, and perform additional integer operations, the "parrallelization" may still make the performance worse.  I think the only use case for improving this would be to use int24 and uint32 along side each other explicitly in the same program, but I'm not so sure adding mantissa to int would be particularly speedy either, at least not enough to warrant the existence of a specific int24 type.  With out the performance consideration then I'm not sure what justifies int10 and int24 and int52.  Right now I'm struggling to find a reason to add arbitrary bit values to the language period.

**Comment by pdaniell-nv** [comment]
Closing the issue. We're not planning to take any action. @Cazadorro please reopen if you object.
