### ISSUE TITLE
How does NV_compute_shader_derivatives relate with variable workgroup sizes?

### ISSUE THREAD

**Issue by cmarcelo** [KhronosGroup/GLSL#68]
The text makes clear that we need to validate the work group size in compile time, so that would exclude variable size work groups.

If that's not the case, what to do when the size is set to something that don't follow the rules for the given arrangement?

Adding a clarification about this could be nice.  (Same comment applies to the corresponding SPV spec)

**Comment by jekstrand** [comment]
+@jeffbolznv

**Comment by jeffbolznv** [comment]
+@nvpbrown

**Comment by nvpbrown** [comment]
@pdaniell-nv  pinged me on this. -- I somehow missed the "+@nvpbrown" update.

The spec didn't consider the interaction between this feature and ARB_compute_variable_group_size, which is obviously an oversight.  It appears that we have three options:

(1) Disallow the use of derivatives in shaders with the "local_size_variable" layout qualifier specified, which can be enforced at compile or link time.

(2) Allow this combination, but add new INVALID_OPERATION errors in DispatchCompute if the group size does not conform to the expectations of the derivatives spec.

(3) Specify that derivatives are undefined if the (variable) group size does not conform to the expectations of the derivatives spec.

Note that approach (2) would not work if we had a form of DispatchCompute that extracted a group size from an indirect buffer, but we intentionally chose not to allow this in ARB_compute_variable_group_size.

Thoughts?  I don't really care greatly how this is resolved.  I personally prefer (3) over (2), because I would prefer not to add another "draw-time" check to the driver.

--

I assume SPIR-V (extension done by @dgkoch) would be affected by this new issue only if we chose (1), and only really to express that the combination of the two features is illegal?  I'm not 100% sure how this all fits in SPIR-V or Vulkan.  It appears that Vulkan may already prohibit variable group sizes:

> For each compute shader entry point, either a LocalSize execution mode or an object
> decorated with the WorkgroupSize decoration must be specified.

Perhaps there could be an issue in the context of SPIR-V outside Vulkan, if "LocalSize" and "WorkgroupSize" are optional.  But the SPIR-V extension for derivative seems to require a "GLCompute" execution model.  However, I don't see anything in the SPIR-V extension that forbids this combination even for *fixed* workgroup sizes.  Would this belong in a "Validation Rules" section of the extension spec?

**Comment by cmarcelo** [comment]
@nvpbrown for the GL spec:

> (2) Allow this combination, but add new INVALID_OPERATION errors in DispatchCompute if the group size does not conform to the expectations of the derivatives spec.

Given we already have other checks for the validity of the values passed to `DispatchComputeGroupSizeARB()`, I think returning `INVALID_VALUE` would be the best choice here.

For the Vulkan spec: in the appendix there is already a rule for this case, so we are good.

For SPIR-V spec: doesn't seem to make restrictions to work-group size, it seems is up to the client APIs.

For ARB_gl_spirv (GL using SPIR-V) and ARB_spirv_extensions specs: they don't specify ARB_compute_variable_group_size, so there's no issue. If they did, `GL_NV_compute_shader_derivatives` could be extended to also modify them and include restrictions similar to what Vulkan has.

**Comment by dgkoch** [comment]
I don't really have a preference for how this is solved on the GL side. 

I agree with @cmarcelo that if we needed to say something about the interactions for SPIR-V that it would need to go into the OpenGL SPIR-V Execution environment (which is defined by ARB_gl_spirv and ARB_spirv_extensions; or the Appendix in GL 4.6), but as you said, I don't believe we've added SPIR-V support for variable group size in any API at this point.

**Comment by pdaniell-nv** [comment]
Is there anything to be done for this issue? If not can it be closed? Thanks.

**Comment by cmarcelo** [comment]
A decision and a PR to fix up the extension text. I volunteer to do the PR if it helps.

@nvpbrown I'd say we go with option (2), my reasoning was

> Given we already have other checks for the validity of the values passed to DispatchComputeGroupSizeARB(), I think returning INVALID_VALUE would be the best choice here.

Works for you?

**Comment by nvpbrown** [comment]
Sorry, I let this get buried.

@pdaniell-nv:  You have any preferences?  I was going to write that we might want to bring this to a Khronos meeting given that an ARB extension is involved, but I suppose NVIDIA can decide this issue ourselves since it's limited to the interaction of an NV extension and the ARB extension.  I looked at the driver and it looks like (2) is at least tractable given that the group size does have to be passed to an API entry point.  I still mildly prefer (3) but can live with (2) if you think that's better.  (It would have the advantage of reporting bad API/shader usage combinations.)

@dgkoch:  I'm not sure what to do about SPIR-V, since it's not clear how you would even express a "GLCompute" shader with a variable workgroup size, let alone use it in the primary target environment (Vulkan).  I suppose one could infer variable workgroup size from the lack of a "LocalSize" or "LocalSizeId" execution mode, though I think that would be a bad idea and it would be better to:

* treat LocalSize (or LocalSizeId) as required
* add a new LocalSizeVariable execution mode for GLCompute if we needed to support the combination

The current OpenGL 4.6 specification has the following validation rule for compute shaders:

– For each compute shader entry point, either a LocalSize execution
mode or an object decorated with the WorkgroupSize decoration
must be specified.

One minor issue is that it doesn't seem to provide for "LocalSizeId".  But the thing that doesn't make sense to me is the part about "or an object decorated with the WorkgroupSize decoration".  This doesn't actually specify the workgroup size -- it specifies a built-in whose value *takes on* the workgroup size.  I think we should delete the "or an object" clause, which would make this issue moot for OpenGL + SPIR-V.  That should probably be tracked by a separate issue, though.

I can prepare extension spec language once we agree on a resolution.

**Comment by pdaniell-nv** [comment]
It sounds like option (2) is probably the most helpful and would be my choice too.

**Comment by dgkoch** [comment]
> @dgkoch: I'm not sure what to do about SPIR-V, since it's not clear how you would even express a "GLCompute" shader with a variable workgroup size, let alone use it in the primary target environment (Vulkan). 

I don't think there is anything we can do for SPIR-V at this point. First, we'd have to add support for variable compute group sizes in SPIR-V, and that would (likely) require a new SPIR-V extension, and API extension to relax the validation rules. Hopefully we can remember to spec this interaction if/when we do that? I guess it wouldn't hurt to write up the proposed interactions as an issue in the compute derivatives extension. 

> One minor issue is that it doesn't seem to provide for "LocalSizeId"

That was added in SPIR-V 1.2, but the OpenGL environment is only defined for SPIR-V 1.1.

**Comment by nvpbrown** [comment]
OK, I'll prepare a change to both the spec and the NVIDIA OpenGL driver for option (2).

@pdaniell-nv @dgkoch Do you agree with the analysis at the end of the previous update that the OpenGL 4.6 SPIR-V validation rule for compute shaders is incorrect?  If so, I can file a Khronos bug reporting this issue.

**Comment by dgkoch** [comment]
> But the thing that doesn't make sense to me is the part about "or an object decorated with the WorkgroupSize decoration". This doesn't actually specify the workgroup size -- it specifies a built-in whose value takes on the workgroup size. I think we should delete the "or an object" clause, which would make this issue moot for OpenGL + SPIR-V. That should probably be tracked by a separate issue, though.

I don't think it's incorrect. We have that exact same language repeated all over the Vulkan spec. 
My recollection on that is hazy, but I think it's because we allow it to be specialized: 

     "The built-in constant vector gl_WorkGroupSize can be specialized using
      the local_size_{xyz}_id qualifiers, to individually give the components
      an id. For example:

          layout(local_size_x_id = 18, local_size_z_id = 19) in;

      "This leaves gl_WorkGroupSize.y as a non-specialization constant, with
      gl_WorkGroupSize being a partially specialized vector.  Its x and z
      components can be later specialized using the ids 18 and 19.  These ids
      are declared independently from declaring the workgroup size:

        layout(local_size_x = 32, local_size_y = 32) in;   // size is (32,32,1)
        layout(local_size_x_id = 18) in;                   // constant_id for x
        layout(local_size_z_id = 19) in;                   // constant_id for z

      "Existing rules for declaring local_size_x, local_size_y, and
      local_size_z are not changed by this extension. For the local-size ids,
      it is a compile-time error to provide different id values for the same
      local-size id, or to provide them after any use.  Otherwise, order,
      placement, number of statements, and replication do not cause errors.

**Comment by nvpbrown** [comment]
Pull request for the spec edits submitted at #85.  The corresponding API extension spec pull request is at:

  https://github.com/KhronosGroup/OpenGL-Registry/pull/298

**Comment by johnkslang** [comment]
Both changes have been merged, closing.
